### ISSUE TITLE
How to do set up the arguments in train_conditional_generator.py?

### ISSUE THREAD

**Issue by ghost** [PaccMann/paccmann_sarscov2#7]
Could you suggest the values for the arguments in train_conditional_generator.py?

error: the following arguments are required: organdb_path, site, clintox_path, sider_path

**Comment by jannisborn** [comment]
Hi @cubicgate,
thanks for your interest in our work :)

It's unclear which version of the code you are running but the arguments you are mentioning should be optional as specified [here](https://github.com/PaccMann/paccmann_generator/blob/d61cd9f1492dd96962c6f86ae1f6a5880071f6fa/examples/affinity/train_conditional_generator.py#L56).

`site` can specify a body organ if you want to optimize molecules against GEPs from particular cell lines.
The other three are paths to pretrained property predictors that can be used to compute additional rewards for the optimization process. OrganDB is for toxicity for a given body organ, clintox predicts probability of FDA approval and failure in clinical stage and sider predicts probabilities for a bunch of drug side effects that usually occur in humans. 

Under the Box link provided in the README you'll find some pretrained models but not those you mentioned because they're optional. You can train them yourself e.g., with the code here: https://github.com/PaccMann/toxsmi

Hope this helps!

**Comment by ghost** [comment]
Hi @jannisborn: I installed the versions using requirements.txt. Because they are not required, so I just deleted them, so it works now. Thanks for your help!
